packages:
  # Telicent only wants mui-icons-material
  - 'packages/mui-icons-material'
  # exclude everything else
  - '!packages/*'
  - '!packages-internal/*'
  - '!apps/*'
  - '!docs'
  - '!test'

patchedDependencies:
  styled-components: patches/styled-components.patch

onlyBuiltDependencies:
  - '@vvago/vale'
